name: Release Build

on:
  push:
    # すべてのブランチを対象に
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/release.yml'
    
# 権限を追加：リリース作成にはcontents: write権限が必要
permissions:
  contents: write

jobs:
  check-commit:
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.check_message.outputs.should_release }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check commit message and version file
        id: check_message
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          
          # [release] が含まれているかチェック
          if [[ "$COMMIT_MSG" != *"[release]"* ]]; then
            echo "should_release=false" >> $GITHUB_OUTPUT
            echo "✅ No [release] tag found - normal commit, no release triggered"
            exit 0
          fi
          
          # js/version.js が変更されているかチェック
          if git diff HEAD~1 --name-only | grep -q "js/version.js"; then
            echo "should_release=true" >> $GITHUB_OUTPUT
            echo "✅ Version file updated with [release] tag - proceeding with release"
          else
            echo "should_release=false" >> $GITHUB_OUTPUT
            echo "❌ Warning: [release] tag found but js/version.js was not modified"
            echo "   This appears to be an accidental [release] tag usage"
            echo "   To trigger a release, please update js/version.js and commit with [release]"
          fi
        shell: bash

  build:
    needs: check-commit
    if: needs.check-commit.outputs.should_release == 'true'
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # キャッシュの設定を追加
      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal

      # macOS環境の最適化
      - name: Configure macOS build environment
        run: |
          echo "CARGO_INCREMENTAL=0" >> $GITHUB_ENV
          echo "CARGO_NET_RETRY=10" >> $GITHUB_ENV
          echo "CARGO_BUILD_JOBS=4" >> $GITHUB_ENV
        shell: bash

      - name: Install dependencies
        run: npm install --no-audit --prefer-offline

      - name: Build the app
        run: npm run tauri build
        env:
          # 並列ビルドを最適化
          CARGO_BUILD_JOBS: 4

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Queuelip-macos-bld
          path: |
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/bundle/macos/*.app
          if-no-files-found: ignore

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          draft: false
          prerelease: false
          files: artifacts/**/*
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true